openapi: 3.0.0
info:
  title: OpenWeatherMap API
  version: 1.0.0
  description: An example Swagger specification for the OpenWeatherMap API

paths:
  /data/2.5/weather:
    get:
      summary: Get weather information by city name and country code
      parameters:
        - name: q
          in: query
          description: City name and country code (e.g., "London,uk")
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  coord:
                    type: object
                    properties:
                      lon:
                        type: number
                      lat:
                        type: number
                  weather:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        main:
                          type: string
                        description:
                          type: string
                        icon:
                          type: string
                  base:
                    type: string
                  main:
                    type: object
                    properties:
                      temp:
                        type: number
                      pressure:
                        type: number
                      humidity:
                        type: number
                      temp_min:
                        type: number
                      temp_max:
                        type: number
                  visibility:
                    type: integer
                  wind:
                    type: object
                    properties:
                      speed:
                        type: number
                      deg:
                        type: number
                  clouds:
                    type: object
                    properties:
                      all:
                        type: integer
                  dt:
                    type: integer
                  sys:
                    type: object
                    properties:
                      type:
                        type: integer
                      id:
                        type: integer
                      country:
                        type: string
                      sunrise:
                        type: integer
                      sunset:
                        type: integer
                  id:
                    type: integer
                  name:
                    type: string
                  cod:
                    type: integer
